[package]
name = "gamekid"
version = "0.1.7"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
env_logger = "0.11.8"
error-iter = "0.4.1"
fastrand = "2.3.0"
log = "0.4.27"
pixels = "0.15.0"
winit = "0.29"
winit_input_helper = "0.15"
